

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning  


  backend:
    build: .
    container_name: todo
    command: sh -c "python manage.py makemigrations --noinput && \
                    python manage.py migrate --noinput && \
                    python manage.py collectstatic --noinput && \
                    gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./.env.stage
    depends_on:
      - redis
      - db

  celery-worker:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - ./core:/app
    env_file:
      - ./.env.stage
    depends_on:
      - backend

  celery-beat:
    build: .
    command: celery -A core beat -l INFO
    volumes:
      - ./core:/app
    env_file:
      - ./.env.stage
    depends_on:
      - backend

  nginx: 
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.stage
volumes:
  static_volume:
  media_volume:
  postgres_data:

 