name: Django Project Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Compose
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DEBUG: ${{secrets.DEBUG}}
        SQL_ENGINE: ${{secrets.SQL_ENGINE}}
        SQL_DATABASE: ${{secrets.SQL_DATABASE}}
        SQL_USER: ${{secrets.SQL_USER}}
        SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
        SQL_HOST: ${{secrets.SQL_HOST}}
        SQL_PORT: ${{secrets.SQL_PORT}}
        EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
        POSTGRES_USER: ${{secrets.POSTGRES_USER}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      run: docker compose -f docker-compose-stage.yml up -d
    - name: Run Tests
      run: docker compose exec backend sh -c "flake8 && pytest ."

  
  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} 
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          docker compose -f docker-compose-stage.yml stop
          git pull
          docker compose -f docker-compose-stage.yml restart
